/**
 * AI-Powered Universal Report Evaluator
 * 
 * Evaluates ANY penetration testing report/writeup with recognizable methodology,
 * even when it doesn't match the app's internal schema.
 * 
 * Core Philosophy:
 * - If content is clearly a pentest report, evaluate it
 * - Don't require strict schema matching
 * - Infer statistics from narrative, commands, findings
 * - Weight every report into user progression analytics
 */

import { DevvAI } from '@devvai/devv-code-backend';
import { CertificationDomain, TechnicalSkill } from '@/store/certification-store';

/**
 * Universal Report Evaluation Result
 * Generated by AI for ANY report format
 */
export interface ReportEvaluation {
  // Classification
  reportType: 'training' | 'professional' | 'external' | 'writeup' | 'partial' | 'custom';
  confidence: number; // 0-100: How confident AI is in the evaluation
  
  // Technical Dimensions (inferred even from partial reports)
  reconnaissance: number; // 0-100
  enumeration: number; // 0-100
  exploitation: number; // 0-100
  privilege_escalation: number; // 0-100
  post_exploitation: number; // 0-100
  
  // Domain Classification (multi-label)
  primaryDomains: CertificationDomain[]; // Most prominent
  secondaryDomains: CertificationDomain[]; // Also present
  
  // Technical Skills Demonstrated
  skillsDetected: TechnicalSkill[];
  skillsInferred: TechnicalSkill[]; // Skills likely used but not explicitly shown
  
  // Reporting Quality
  structureQuality: number; // 0-100
  clarityScore: number; // 0-100
  reproducibility: number; // 0-100: Could someone else reproduce the attack?
  commandEvidence: number; // 0-100: Quality of command documentation
  methodologyConsistency: number; // 0-100: Following PTES/OWASP/etc.
  
  // Quality Signals (boolean detections)
  hasCommands: boolean;
  hasAttackChain: boolean;
  hasProofOfConcept: boolean;
  hasFlags: boolean;
  hasRemediation: boolean;
  hasValidationSteps: boolean;
  
  // Content Richness
  commandCount: number;
  discoveredItems: number; // Ports + services + creds + flags
  narrativeDepth: 'minimal' | 'adequate' | 'comprehensive';
  
  // Overall Assessment
  overallQuality: number; // 0-100 composite score
  statisticalWeight: number; // 0-1: How much this report should affect analytics
  
  // Actionable Insights
  strengths: string[]; // What was done well
  weaknesses: string[]; // What could be improved
  recommendations: string[]; // Next steps for skill development
  
  // Metadata
  estimatedDuration: number; // Estimated hours spent (AI inference)
  difficultyEstimate: 'beginner' | 'intermediate' | 'advanced';
  
  // Reasoning (for debugging)
  reasoning: string;
}

/**
 * Fallback evaluation when AI fails
 * Provides heuristic-based scoring
 */
function generateFallbackEvaluation(markdown: string): ReportEvaluation {
  console.log('[AI EVALUATOR] Generating fallback evaluation (heuristic-based)');
  
  const content = markdown.toLowerCase();
  const length = markdown.length;
  
  // Heuristic detections
  const hasCommands = /```|`[^`]{10,}`|nmap|gobuster|sqlmap/.test(markdown);
  const hasFlags = /THM\{|HTB\{|FLAG\{|user\.txt|root\.txt/.test(markdown);
  const hasCreds = /password|credential|username.*:|.*:.*password/i.test(markdown);
  const hasMethodology = /methodology|approach|attack.*path|ptes|owasp/i.test(content);
  
  // Count approximate items
  const commandCount = (markdown.match(/```/g) || []).length / 2 + 
                       (markdown.match(/`[^`]{10,}`/g) || []).length;
  
  const portCount = (markdown.match(/\b\d+\/tcp\b/g) || []).length;
  const serviceCount = (markdown.match(/ssh|http|smb|ldap|mysql|rdp/gi) || []).length;
  const credCount = (markdown.match(/[a-z]+:[a-z0-9!@#$%]+/gi) || []).length;
  const flagCount = (markdown.match(/THM\{|HTB\{|FLAG\{/g) || []).length;
  
  const discoveredItems = portCount + serviceCount + credCount + flagCount;
  
  // Domain inference
  const domains: CertificationDomain[] = [];
  if (/nmap|scan|recon/i.test(content)) domains.push('reconnaissance');
  if (/enumerat|gobuster|dirb/i.test(content)) domains.push('enumeration');
  if (/web|http|sql|xss|burp/i.test(content)) domains.push('web_exploitation');
  if (/privesc|sudo|suid|escalat/i.test(content)) domains.push('privilege_escalation');
  if (/kerberos|ldap|smb.*lateral|pass.*hash/i.test(content)) domains.push('lateral_movement');
  if (/password|brute|hydra|crack/i.test(content)) domains.push('password_attacks');
  
  // Scoring
  const contentScore = Math.min(100, 
    Math.floor(length / 50) + // Length bonus
    (commandCount * 5) +
    (discoveredItems * 3) +
    (hasFlags ? 20 : 0) +
    (hasMethodology ? 15 : 0)
  );
  
  return {
    reportType: 'custom',
    confidence: 60, // Moderate confidence in heuristics
    
    reconnaissance: hasCommands && /nmap|scan/i.test(content) ? 70 : 40,
    enumeration: hasCommands && /gobuster|enum/i.test(content) ? 70 : 40,
    exploitation: hasCreds || hasFlags ? 70 : 40,
    privilege_escalation: hasFlags && /root|admin|privesc/i.test(content) ? 75 : 40,
    post_exploitation: /post.*exploit|persistence|pivot/i.test(content) ? 65 : 35,
    
    primaryDomains: domains.slice(0, 2) as CertificationDomain[],
    secondaryDomains: domains.slice(2) as CertificationDomain[],
    
    skillsDetected: [],
    skillsInferred: [],
    
    structureQuality: hasMethodology ? 70 : 50,
    clarityScore: length > 1000 ? 65 : 50,
    reproducibility: hasCommands ? 70 : 40,
    commandEvidence: commandCount > 5 ? 75 : commandCount > 0 ? 50 : 30,
    methodologyConsistency: hasMethodology ? 70 : 40,
    
    hasCommands,
    hasAttackChain: hasCommands && discoveredItems > 3,
    hasProofOfConcept: hasFlags || (hasCreds && hasCommands),
    hasFlags,
    hasRemediation: /remediat|fix|patch|recommend/i.test(content),
    hasValidationSteps: /verify|validate|confirm|test/i.test(content),
    
    commandCount: Math.floor(commandCount),
    discoveredItems,
    narrativeDepth: length > 3000 ? 'comprehensive' : length > 1000 ? 'adequate' : 'minimal',
    
    overallQuality: contentScore,
    statisticalWeight: Math.min(1.0, contentScore / 100),
    
    strengths: [
      hasCommands ? 'Command documentation present' : null,
      hasFlags ? 'Objectives achieved (flags captured)' : null,
      discoveredItems > 5 ? 'Thorough information gathering' : null,
    ].filter(Boolean) as string[],
    
    weaknesses: [
      !hasCommands ? 'Limited command documentation' : null,
      !hasMethodology ? 'Methodology not clearly documented' : null,
      commandCount < 5 ? 'Could include more technical details' : null,
    ].filter(Boolean) as string[],
    
    recommendations: [
      'Document complete command history',
      'Include methodology explanation',
      'Add proof of concept evidence',
    ],
    
    estimatedDuration: Math.max(0.5, Math.floor(discoveredItems / 3)),
    difficultyEstimate: discoveredItems > 10 ? 'advanced' : discoveredItems > 5 ? 'intermediate' : 'beginner',
    
    reasoning: 'Heuristic-based evaluation (AI unavailable)',
  };
}

/**
 * Evaluate any penetration testing report using AI
 * 
 * Accepts:
 * - Internal training reports
 * - Professional pentest reports
 * - External writeups (TryHackMe/HackTheBox)
 * - Partial/custom reports
 * - Any markdown with recognizable pentest content
 */
export async function evaluateReport(
  markdown: string,
  metadata?: {
    title?: string;
    date?: string;
    domain?: string;
    existingParsedData?: any;
  }
): Promise<ReportEvaluation> {
  try {
    console.log('[AI EVALUATOR] Starting evaluation for report:', markdown.length, 'chars');
    
    // Validate minimum content
    if (!markdown || markdown.length < 100) {
      throw new Error('Report too short for evaluation (minimum 100 characters)');
    }
    
    // Extract key content sections for AI analysis (limit to 8000 chars to fit in prompt)
    const contentSample = markdown.length > 8000 
      ? markdown.substring(0, 4000) + '\n\n[... content truncated ...]\n\n' + markdown.substring(markdown.length - 4000)
      : markdown;
    
    // Count observable items for AI context
    const observableCommandCount = (markdown.match(/```/g) || []).length / 2;
    const observableFlagCount = (markdown.match(/THM\{|HTB\{|FLAG\{|user\.txt|root\.txt/gi) || []).length;
    const observableCredCount = (markdown.match(/[a-z0-9_-]+:[a-zA-Z0-9!@#$%^&*()_+-=]{4,}/gi) || []).length;
    
    // Prepare AI evaluation prompt
    const ai = new DevvAI();
    
    const systemPrompt = `You are an expert penetration testing report evaluator. Your role is to assess ANY penetration testing report or writeup, regardless of format.

CRITICAL INSTRUCTIONS:
1. Evaluate even if the report doesn't match a specific schema
2. Infer technical proficiency from narrative, commands, findings, and methodology
3. Be generous but accurate - the goal is to help users track real skill progression
4. If something is clearly a pentest report with ANY recognizable methodology, evaluate it
5. Respond with ONLY valid JSON (no markdown blocks, no extra text)

OBSERVABLE CONTEXT:
- Report length: ${markdown.length} characters
- Code blocks detected: ${observableCommandCount}
- Flags detected: ${observableFlagCount}
- Credentials detected: ${observableCredCount}
- Provided title: ${metadata?.title || 'Unknown'}
- Suggested domain: ${metadata?.domain || 'Unknown'}

YOUR EVALUATION MUST BE EVIDENCE-BASED:
- reconnaissance: Score reconnaissance quality (0-100) based on information gathering shown
- enumeration: Score enumeration depth (0-100) based on service/directory discovery
- exploitation: Score exploitation skill (0-100) based on successful attacks/credentials found
- privilege_escalation: Score privesc ability (0-100) based on privilege gains shown
- post_exploitation: Score post-exploit work (0-100) based on persistence/pivoting shown

RESPONSE FORMAT (pure JSON, no markdown):
{
  "reportType": "training|professional|external|writeup|partial|custom",
  "confidence": 0-100,
  "reconnaissance": 0-100,
  "enumeration": 0-100,
  "exploitation": 0-100,
  "privilege_escalation": 0-100,
  "post_exploitation": 0-100,
  "primaryDomains": ["domain1", "domain2"],
  "secondaryDomains": ["domain3"],
  "structureQuality": 0-100,
  "clarityScore": 0-100,
  "reproducibility": 0-100,
  "commandEvidence": 0-100,
  "methodologyConsistency": 0-100,
  "hasCommands": boolean,
  "hasAttackChain": boolean,
  "hasProofOfConcept": boolean,
  "hasFlags": boolean,
  "hasRemediation": boolean,
  "hasValidationSteps": boolean,
  "commandCount": number,
  "discoveredItems": number,
  "narrativeDepth": "minimal|adequate|comprehensive",
  "overallQuality": 0-100,
  "statisticalWeight": 0.0-1.0,
  "strengths": ["strength1", "strength2"],
  "weaknesses": ["weakness1"],
  "recommendations": ["rec1", "rec2"],
  "estimatedDuration": 0.5-8.0,
  "difficultyEstimate": "beginner|intermediate|advanced",
  "reasoning": "Brief explanation of your assessment"
}`;

    const userPrompt = `Evaluate this penetration testing report:

---
${contentSample}
---

Remember: Respond with ONLY the JSON object. No markdown blocks, no extra text.`;

    // Call AI for evaluation
    const response = await ai.chat.completions.create({
      model: 'kimi-k2-0711-preview',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.3, // Deterministic for consistency
      max_tokens: 2000,
    });
    
    const aiContent = response.choices[0]?.message?.content || '{}';
    console.log('[AI EVALUATOR] Raw AI response (first 500 chars):', aiContent.substring(0, 500));
    
    // Parse AI response (handle markdown blocks if present)
    let evaluation: any;
    try {
      // Strip markdown code blocks if present
      const jsonMatch = aiContent.match(/```(?:json)?\s*({[\s\S]*?})\s*```/) || 
                        aiContent.match(/({[\s\S]*})/);
      
      if (!jsonMatch) {
        throw new Error('No JSON found in AI response');
      }
      
      evaluation = JSON.parse(jsonMatch[1]);
    } catch (parseError) {
      console.error('[AI EVALUATOR] JSON parse error:', parseError);
      console.error('[AI EVALUATOR] Failed content:', aiContent);
      
      // Fallback to heuristic evaluation
      return generateFallbackEvaluation(markdown);
    }
    
    // Validate and normalize AI response
    const normalizedEvaluation: ReportEvaluation = {
      reportType: evaluation.reportType || 'custom',
      confidence: Math.max(0, Math.min(100, evaluation.confidence || 70)),
      
      reconnaissance: Math.max(0, Math.min(100, evaluation.reconnaissance || 50)),
      enumeration: Math.max(0, Math.min(100, evaluation.enumeration || 50)),
      exploitation: Math.max(0, Math.min(100, evaluation.exploitation || 50)),
      privilege_escalation: Math.max(0, Math.min(100, evaluation.privilege_escalation || 50)),
      post_exploitation: Math.max(0, Math.min(100, evaluation.post_exploitation || 50)),
      
      primaryDomains: (evaluation.primaryDomains || []).slice(0, 3),
      secondaryDomains: (evaluation.secondaryDomains || []).slice(0, 3),
      
      skillsDetected: evaluation.skillsDetected || [],
      skillsInferred: evaluation.skillsInferred || [],
      
      structureQuality: Math.max(0, Math.min(100, evaluation.structureQuality || 60)),
      clarityScore: Math.max(0, Math.min(100, evaluation.clarityScore || 60)),
      reproducibility: Math.max(0, Math.min(100, evaluation.reproducibility || 50)),
      commandEvidence: Math.max(0, Math.min(100, evaluation.commandEvidence || 50)),
      methodologyConsistency: Math.max(0, Math.min(100, evaluation.methodologyConsistency || 50)),
      
      hasCommands: !!evaluation.hasCommands,
      hasAttackChain: !!evaluation.hasAttackChain,
      hasProofOfConcept: !!evaluation.hasProofOfConcept,
      hasFlags: !!evaluation.hasFlags,
      hasRemediation: !!evaluation.hasRemediation,
      hasValidationSteps: !!evaluation.hasValidationSteps,
      
      commandCount: Math.max(0, evaluation.commandCount || 0),
      discoveredItems: Math.max(0, evaluation.discoveredItems || 0),
      narrativeDepth: evaluation.narrativeDepth || 'adequate',
      
      overallQuality: Math.max(0, Math.min(100, evaluation.overallQuality || 60)),
      statisticalWeight: Math.max(0, Math.min(1, evaluation.statisticalWeight || 0.7)),
      
      strengths: (evaluation.strengths || []).slice(0, 5),
      weaknesses: (evaluation.weaknesses || []).slice(0, 5),
      recommendations: (evaluation.recommendations || []).slice(0, 5),
      
      estimatedDuration: Math.max(0.25, Math.min(12, evaluation.estimatedDuration || 1)),
      difficultyEstimate: evaluation.difficultyEstimate || 'intermediate',
      
      reasoning: evaluation.reasoning || 'AI evaluation completed',
    };
    
    console.log('[AI EVALUATOR] ✅ Successfully evaluated report:', {
      type: normalizedEvaluation.reportType,
      confidence: normalizedEvaluation.confidence,
      overallQuality: normalizedEvaluation.overallQuality,
      weight: normalizedEvaluation.statisticalWeight,
      domains: normalizedEvaluation.primaryDomains,
    });
    
    return normalizedEvaluation;
    
  } catch (error) {
    console.error('[AI EVALUATOR] Evaluation failed:', error);
    
    // Always provide fallback - NEVER reject a report
    return generateFallbackEvaluation(markdown);
  }
}

/**
 * Convert AI evaluation to certification update data
 * This maps AI evaluation results to the format expected by certification store
 */
export function evaluationToCertificationUpdate(
  evaluation: ReportEvaluation,
  existingData?: any,
  customDate?: string
): {
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  commands: Array<{ command: string; phase: string; correct: boolean }>;
  evaluation: {
    reconScore: number;
    scanningScore: number;
    enumerationScore: number;
    exploitationScore: number;
    privescScore: number;
    methodologyScore: number;
    overallScore: number;
  };
  flags_captured: number;
  hints_used: number;
  missed_steps: string[];
  domains_practiced: CertificationDomain[];
  discovered_info?: {
    openPorts?: string[];
    services?: string[];
    directories?: string[];
    credentials?: string[];
    flags?: string[];
  };
  customDate?: string;
} {
  // Generate placeholder commands if none exist
  const commands = existingData?.commands || [];
  if (commands.length === 0 && evaluation.commandCount > 0) {
    // Create representative commands based on domains
    for (let i = 0; i < Math.min(evaluation.commandCount, 10); i++) {
      commands.push({
        command: `[Command ${i + 1} - see imported report]`,
        phase: 'enumeration',
        correct: true,
      });
    }
  }
  
  return {
    difficulty: evaluation.difficultyEstimate,
    commands,
    evaluation: {
      reconScore: evaluation.reconnaissance,
      scanningScore: evaluation.reconnaissance, // Recon often includes scanning
      enumerationScore: evaluation.enumeration,
      exploitationScore: evaluation.exploitation,
      privescScore: evaluation.privilege_escalation,
      methodologyScore: evaluation.methodologyConsistency,
      overallScore: evaluation.overallQuality,
    },
    flags_captured: evaluation.hasFlags ? (existingData?.discoveredInfo?.flags?.length || 1) : 0,
    hints_used: 0, // External reports don't have hints
    missed_steps: evaluation.weaknesses,
    domains_practiced: [...evaluation.primaryDomains, ...evaluation.secondaryDomains],
    discovered_info: existingData?.discoveredInfo || {
      openPorts: [],
      services: [],
      directories: [],
      credentials: [],
      flags: [],
    },
    customDate: customDate, // CRITICAL: Pass custom date for imported reports
  };
}
