/**
 * PT1 Section Report Generator
 * 
 * Generates comprehensive Markdown reports for individual PT1 exam sections
 */

import type { PT1Section, SectionEvaluation, CommandEntry, ExamSession } from '@/store/exam-session-store';
import { getSectionDisplayName } from './download-helpers';

export interface SectionReportData {
  section: PT1Section;
  evaluation: SectionEvaluation;
  examSession: ExamSession;
}

/**
 * Generates a complete Markdown report for a PT1 section
 */
export function generateSectionReport(
  section: PT1Section,
  evaluation: SectionEvaluation,
  examSession: ExamSession
): string {
  const sectionName = getSectionDisplayName(section);
  const duration = Math.floor(examSession.elapsedSeconds / 60);
  const timestamp = new Date().toISOString();
  const targetIP = examSession.scenario?.targetIP || 'Unknown';
  
  // Find section-specific data from completedSections
  const sectionData = examSession.completedSections.find(s => s.sectionId === section);
  const sectionCommands = sectionData?.commandHistory || examSession.commandHistory;
  const sectionDuration = sectionData?.duration ? Math.floor(sectionData.duration / 60) : duration;
  
  const report = `# PT1 Section Report: ${sectionName}

## Section Metadata

- **Section**: ${sectionName}
- **Score**: ${evaluation.score}%
- **Target IP**: ${targetIP}
- **Duration**: ${sectionDuration} minutes
- **Commands Executed**: ${sectionCommands.length}
- **Flags Found**: ${examSession.flagsFound}
- **Hints Used**: ${examSession.hintsUsed}
- **Completed At**: ${timestamp.split('T')[0]} ${timestamp.split('T')[1].substring(0, 8)}
- **Evaluation Generated**: ${evaluation.generatedAt}

---

## Evaluation Summary

### Overall Performance

**Score: ${evaluation.score}%**

${getScoreInterpretation(evaluation.score)}

---

### ✅ Strengths

${evaluation.strengths.length > 0 
  ? evaluation.strengths.map((s, i) => `${i + 1}. ${s}`).join('\n')
  : '- No specific strengths identified'}

---

### ⚠️ Weaknesses

${evaluation.weaknesses.length > 0
  ? evaluation.weaknesses.map((w, i) => `${i + 1}. ${w}`).join('\n')
  : '- No major weaknesses identified'}

---

### 🔍 Missed Opportunities

${evaluation.missedOpportunities.length > 0
  ? evaluation.missedOpportunities.map((m, i) => `${i + 1}. ${m}`).join('\n')
  : '- No significant missed opportunities'}

---

### 📋 Methodology Issues

${evaluation.methodologyIssues.length > 0
  ? evaluation.methodologyIssues.map((issue, i) => `${i + 1}. ${issue}`).join('\n')
  : '- No major methodology issues identified'}

---

### 💡 Improvement Suggestions

${evaluation.improvementSuggestions.length > 0
  ? evaluation.improvementSuggestions.map((suggestion, i) => `${i + 1}. ${suggestion}`).join('\n')
  : '- Continue practicing current methodology'}

---

## Command History

### Execution Timeline

${sectionCommands.length > 0
  ? sectionCommands.map((cmd, i) => generateCommandEntry(cmd, i + 1)).join('\n---\n')
  : '*No commands executed in this section*'}

---

## Report Draft

${examSession.reportDraft.length > 0
  ? examSession.reportDraft
  : '*No report draft written for this section*'}

---

## Next Steps

Based on your performance in this section, focus on:

${generateNextSteps(evaluation)}

---

*Generated by SeshForge PT1 Training Platform*  
*Section: ${sectionName}*  
*This is a practice exam section report for certification preparation*
`;

  return report;
}

/**
 * Helper: Generate individual command entry
 */
function generateCommandEntry(cmd: CommandEntry, index: number): string {
  const timestamp = new Date(cmd.timestamp).toLocaleTimeString();
  
  return `
### Command ${index}

**Executed at:** ${timestamp}

\`\`\`bash
${cmd.command}
\`\`\`

**Output:**

\`\`\`
${cmd.output.substring(0, 500)}${cmd.output.length > 500 ? '\n...[truncated]' : ''}
\`\`\`
`;
}

/**
 * Helper: Get score interpretation
 */
function getScoreInterpretation(score: number): string {
  if (score >= 85) {
    return '**Excellent performance!** You demonstrated strong competence in this domain with minimal issues. This level of performance indicates PT1 exam readiness for this section.';
  } else if (score >= 70) {
    return '**Good performance.** You showed solid understanding with some areas for improvement. With focused practice on the identified weaknesses, you should be well-prepared for this PT1 exam section.';
  } else if (score >= 55) {
    return '**Moderate performance.** You have foundational skills but need significant practice in this domain. Review the missed opportunities and work on methodology adherence before attempting the real PT1 exam.';
  } else if (score >= 40) {
    return '**Below average performance.** This section requires substantial additional practice. Focus on fundamental methodology and tool usage before progressing. Consider targeted drills in this domain.';
  } else {
    return '**Needs significant improvement.** This section demonstrates major gaps in knowledge and methodology. Comprehensive study and practice drills are required before attempting certification-level work in this domain.';
  }
}

/**
 * Helper: Generate next steps based on evaluation
 */
function generateNextSteps(evaluation: SectionEvaluation): string {
  const steps: string[] = [];
  
  // Add improvement suggestions as primary next steps
  if (evaluation.improvementSuggestions.length > 0) {
    steps.push(...evaluation.improvementSuggestions.slice(0, 3));
  }
  
  // If score is low, add general recommendations
  if (evaluation.score < 70) {
    steps.push('Review PTES/OSSTMM methodology for this domain');
    steps.push('Practice tool usage with guided Command Drills');
  }
  
  // If methodology issues exist, prioritize those
  if (evaluation.methodologyIssues.length > 0) {
    steps.push('Study professional pentesting methodology standards');
  }
  
  // Add missed opportunities as learning targets
  if (evaluation.missedOpportunities.length > 0 && steps.length < 5) {
    steps.push(`Address missed opportunities: ${evaluation.missedOpportunities[0]}`);
  }
  
  return steps.length > 0
    ? steps.map((step, i) => `${i + 1}. ${step}`).join('\n')
    : '1. Continue practicing this domain\n2. Attempt more complex scenarios\n3. Review professional pentesting reports';
}
